name: lint

on:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Run Linter(ESLint)
        run: |
          yarn install
          yarn lint
