name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Run Linter(ESLint)
        run: |
          yarn install
          yarn lint
