name: Version Increment
on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'chore(deps): update all 🚀') || contains(github.event.head_commit.message, 'chore/update-dependencies')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Github config credentials
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
      - name: Increment version
        run: |
          npm --no-git-tag-version version patch
          NPM_PACKAGE_VERSION=$(npm --silent run node -- --print process.env.npm_package_version)
          git add package.json
          git commit -m "[RELEASE] $NPM_PACKAGE_VERSION"
          git push
