name: Version Increment
on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'chore(deps): update all 🚀') || contains(github.event.head_commit.message, 'chore/update-dependencies')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Github config credentials
        run: git config --global user.name 'GitHub Actions <actions@github.com>'
      - run: git config --global user.email 'GitHub Actions <actions@github.com>'
      - name: increment version
        run: npm version patch -m "[RELEASE] %s"
      - run: git push --force
